// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1tE_3gPazM_NzQJ7vmEnozTs65u-Wthk',
    appId: '1:1065147892162:web:e643a92845d641d492165b',
    messagingSenderId: '1065147892162',
    projectId: 'assessment-software-senai',
    authDomain: 'assessment-software-senai.firebaseapp.com',
    storageBucket: 'assessment-software-senai.firebasestorage.app',
    measurementId: 'G-NPJ6RSHL9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3v6AMo4G1vy_mKG5iNG8fIWHWXTotvok',
    appId: '1:1065147892162:android:2581cbd10156c35292165b',
    messagingSenderId: '1065147892162',
    projectId: 'assessment-software-senai',
    storageBucket: 'assessment-software-senai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-lMjzdkJgRs5jozjk7_VqJhRnYNs61Zo',
    appId: '1:1065147892162:ios:378422f5d7f37f2892165b',
    messagingSenderId: '1065147892162',
    projectId: 'assessment-software-senai',
    storageBucket: 'assessment-software-senai.firebasestorage.app',
    iosBundleId: 'com.example.assessmentSoftwareSenai',
  );
}
